In [1]:
#import numpy

In [6]:
import numpy as np # with alias

In [8]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
Height = [5.6,6.1,4.5,6.2,4.9]
Height


[5.6, 6.1, 4.5, 6.2, 4.9]

In [10]:
Weight = [65,78,34,65,56]
Weight

[65, 78, 34, 65, 56]

In [11]:
# bmi = weight / height ** 2
Weight / Height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
import numpy as np
print("Before Conversion Into Numpy")
print(type(Height))
print(Height)
Height = np.array(Height)
print("After Conversion Into Numpy")
print(type(Height))
print(Height)
Weight = np.array(Weight)

Before Conversion Into Numpy
<class 'list'>
[5.6, 6.1, 4.5, 6.2, 4.9]
After Conversion Into Numpy
<class 'numpy.ndarray'>
[5.6 6.1 4.5 6.2 4.9]


In [13]:
print(type(Weight))
print(Weight)

<class 'numpy.ndarray'>
[65 78 34 65 56]


In [14]:
BMI = Weight / Height ** 2

In [15]:
print(BMI)

[2.07270408 2.0962107  1.67901235 1.69094693 2.33236152]


In [17]:
U = [1,2,3,4,5,6]
V = [7,8,9,0,1,2]
# W = [8 , 10 , 12 , 4 , 6 , 8]
# W = [7 , 16 , 27 , 0 , 5 , 12]

W = U * V
print(W)

TypeError: can't multiply sequence by non-int of type 'list'

In [19]:
U = np.array(U)
V = np.array(V)
W = U * V
print(W)

[ 7 16 27  0  5 12]


In [23]:
List = [5,7,34,56,32,65]
#List > 35
List = np.array(List)
List > 35

array([False, False, False,  True, False,  True])

In [26]:
List[List > 35]

array([56, 65])

In [27]:
W = np.array([U,V])
W

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2]])

In [28]:
W.shape

(2, 6)

In [29]:
W[0]

array([1, 2, 3, 4, 5, 6])

In [30]:
W[0][0]

1

In [31]:
W[0][1]

2

In [32]:
W[0][2]

3

In [33]:
W[0][3]

4

In [34]:
W[1]

array([7, 8, 9, 0, 1, 2])

In [35]:
W[1][0]

7

In [36]:
W[1][4]

1

In [37]:
R1_Mean = W[0].mean() 
R2_Mean =W[1].mean()

In [38]:
R1_Mean

3.5

In [39]:
R2_Mean

4.5

In [40]:
R1_Sum = W[0].sum()
R2_Sum = W[1].sum()
R1_Sum

21

In [41]:
R2_Sum

27

In [43]:
R1_Med = np.median(W[0])
R1_Med

3.5

In [44]:
R2_Med = np.median(W[1])
R2_Med

4.5

In [45]:
R2_Std = np.std(W[1])
R2_Std

3.593976442141304

In [53]:
height = np.random.normal(5, 3, 6)
height = np.round(height , 2)
print(height)
weight = np.round(np.random.normal(60, 30, 5), 1)
print(weight)


[ 1.93  6.8   6.08 10.65  3.68  8.41]
[ 56.8  71.5  49.2  64.1 117.1]
